#!/usr/bin/env bash
# install load balancer

# colors
blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

echo -e "${blue}Updating and doing some minor checks...${reset}\n"

function install() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "    Installing: ${brown}$1${reset}\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    ${green}${1} is already installed.${reset}\n"
    fi
}

install haproxy

echo -e "\n${blue}Setting up some minor stuff.${reset}\n"

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 119047-web-01 54.174.89.177 check
    server 119047-web-02 100.25.223.50 check
"

echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# enable haproxy to be started by init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

if ! sudo systemctl is-active --quiet haproxy; then
    sudo systemctl start haproxy
else
    sudo systemctl restart haproxy
fi
